PATHS:
  HOLDINGS: 'quotes/holdings/'
  YAHOO_PATH: 'quotes/yahoo_data/'
  COINS_DATA: 'quotes/coins/'
  COMMON_IMG_PATH: 'img/'
  RESULTS_PATH: 'results/'
  IMAGES_OUT_PATH: 'results/img_out/'
  LOGS: 'logs/'
  WEBDRIVER: 'webdriver/'
  ETF_HOLDINGS_URL: 'https://www.barchart.com/stocks/quotes/{}/constituents?page=all'
  CHARTER_IMAGES_PATH: 'results/port_images/'
  STATS_PATH: 'results/strategy_stats/'


TELEGRAM:
  API_KEY: '1606389'
  API_HASH: '1df2a687294d0003275a394b52296186'
  TELETHON_DB_NAME: 'telethon_upsilon_db'
  TEST_IP: '149.154.167.40:443'
  PROD_IP: '149.154.167.50:443'
  UPSILON: '1417206041:AAHqQK99vhYOqJpMZLDybUkC6aDaS4qsEsQ'
  OWNER: '379634398'
  SERVICE_CHAT: '-1001262211476'
  PAYMENT_TOKEN: '18c09e066f974297975b8191a8994da7'
  PAYMENT_SUCCESS_LISTEN: '0.0.0.0'
  PAYMENT_SUCCESS_LISTEN_PORT: '8445'
  TARIFF_IMAGES: 'results/tariff_images/'

SQL:
  DB_NAME: 'upsilon_one'
  DB_USER: 'upsilon_one'
  DB_PASSWORD: 'showmethemoney'
  DB_HOST: 'localhost'
  DB_PORT: '3306'
  DEFAULT_START_QUOTES_DATE: '2006-01-01'

SQL_TABLE_NAMES:
  QUOTE_TABLE_NAME: 'quotes'
  UNIVERSE_TABLE_NAME: 'universe'
  PORTFOLIO_ALLOCATION_TABLE_NAME: 'allocations'
  PORTFOLIO_RETURNS_TABLE_NAME: 'returns'
  PORTFOLIO_BARS_TABLE_NAME: 'portfolio_bars'

DIALOGFLOW:
  PROJECT_ID: 'common-bot-1'

COINMARKETCAP:
  KEY: 'c9547ad5-593a-4cb0-88a4-8189d9b3807e'


CREDENTIALS:
  BTC: '__BTC:__ 185eQAq1oNiyt7NkVkVirnwztWfFAqLpwS'
  ETH: '__ETH:__ 0xd1937B37A820C7e2edf0ee11cEf057796c15d87D'

EODHISTOCICALDATA:
  API_KEY: '5fdf760e9148c0.04477443'


ETF_FOR_SCRAPE: {
                  'QQQ': 20,
                  'IWY': 20,
                  'FDN': 20,
                  'QCLN': 20,
                  'ARKW': 15,
                  'ARKK': 15,
                  'ARKF': 15,
                  'ARKG': 15
}

ETFs: [
    'QQQ',
    'QLD',
    'SSO',
    'XLY',
    'TLT',
    'IEF',
    'TMF',
    'FDN',
    'ARKW',
    'QCLN',
    'SPY',
    'XBI',
    'GLD',
    'LQD',
    'XLP',

]

VALID_EXCHANGE: [
  'NASDAQ',
  'NYSE',
  'AMEX',
  'US'
]
EXCLUDE_SECTORS: [
  'Financial Services',
  'Real Estate',
  'Financial',
  'Energy',
  'Other'
]

NOT_EXCLUDE_TICKERS: [
  'PYPL',
  'MA',
  'V'
]


CHARTER_CANDLE_CHART:
  IMAGE_WIDTH: 640
  IMAGE_HEIGHT: 320
  TITLE_FONT_COLOR: 0x5fFFFFFF
  EXTRA_DAYS: 5
  AXIS_FONT_COLOR: 0x5fFFFFFF
  CHART_BACKGROUND_COLOR: 0x000000
  OUTER_BACKGROUND_COLOR: 0x000000
  GRID_LINE_COLOR: 0xcdd9d9d9
  WATERMARK_TEXT_COLOR: 0xf1d9d9d9
  CANDLE_UP_COLOR: 0x38761D
  CANDLE_DOWN_COLOR: 0xff0000
  CANDLE_SHADOW_COLOR: 0x9eB5B5B8
  COMPARISON_LINE_COLOR: 0xff7f27

CHARTER_HISTOGRAM:
  IMAGE_WIDTH: 640
  IMAGE_HEIGHT: 250
  HIST_BACKGROUND_COLOR: 0x000000
  AXIS_FONT_COLOR: 0x5fFFFFFF
  TITLE_FONT_COLOR: 0x5fFFFFFF
  WATERMARK_TEXT_COLOR: 0xcdd9d9d9
  BAR_UP_COLOR: 0x38761D
  BAR_DOWN_COLOR: 0xff0000

CHARTER_PIE:
  IMAGE_WIDTH: 640
  IMAGE_HEIGHT: 325
  PIE_BACKGROUND_COLOR: 0x000000
  TITLE_FONT_COLOR: 0x5fFFFFFF
  OUTER_BACKGROUND_COLOR: 0x000000
  AXIS_FONT_COLOR: 0x5fFFFFFF


PORTFOLIOS:
  PARKING: ['QQQ', 'XBI', 'XLY', 'TLT', 'IEF'] # RS-1m, VOl-21d, 4/5 to hold
# 'https://www.portfoliovisualizer.com/test-market-timing-model?s=y&coreSatellite=false&timingModel=9&timePeriod=4&startYear=2007&firstMonth=1&endYear=2020&lastMonth=12&calendarAligned=true&includeYTD=false&initialAmount=10000&periodicAdjustment=0&adjustmentAmount=0&inflationAdjusted=true&adjustmentPercentage=0.0&adjustmentFrequency=4&symbols=XBI+XLY+QQQ+IEF+TLT&singleAbsoluteMomentum=false&volatilityTarget=6.0&downsideVolatility=false&outOfMarketStartMonth=5&outOfMarketEndMonth=10&outOfMarketAssetType=2&outOfMarketAsset=IEF&movingAverageSignal=1&movingAverageType=1&multipleTimingPeriods=false&periodWeighting=2&windowSize=1&windowSizeInDays=105&movingAverageType2=1&windowSize2=10&windowSizeInDays2=105&excludePreviousMonth=false&normalizeReturns=false&volatilityWindowSize=-1&volatilityWindowSizeInDays=21&assetsToHold=4&allocationWeights=4&riskControlType=0&riskWindowSize=10&riskWindowSizeInDays=0&rebalancePeriod=1&separateSignalAsset=false&tradeExecution=0&comparedAllocation=0&benchmark=-1&benchmarkSymbol=TLT&timingPeriods%5B0%5D=5&timingUnits%5B0%5D=2&timingWeights%5B0%5D=100&timingUnits%5B1%5D=2&timingWeights%5B1%5D=0&timingUnits%5B2%5D=2&timingWeights%5B2%5D=0&timingUnits%5B3%5D=2&timingWeights%5B3%5D=0&timingUnits%5B4%5D=2&timingWeights%5B4%5D=0&volatilityPeriodUnit=2&volatilityPeriodWeight=0&symbol1=XLV&allocation1_1=20&symbol2=XLY&allocation2_1=20&symbol3=IEF&allocation3_1=20&symbol5=TLT&allocation5_1=20&symbol6=QQQ&allocation6_1=20'
  ALL_WEATHER: ['QQQ', 'SPY', 'XLY', 'XBI', 'TLT', 'GLD'] # RS-1m, VOl-21d, 4/7 to hold
# 'https://www.portfoliovisualizer.com/test-market-timing-model?s=y&coreSatellite=false&timingModel=9&timePeriod=4&startYear=2007&firstMonth=1&endYear=2020&lastMonth=12&calendarAligned=true&includeYTD=false&initialAmount=10000&periodicAdjustment=0&adjustmentAmount=0&inflationAdjusted=true&adjustmentPercentage=0.0&adjustmentFrequency=4&symbols=QQQ+SPY+XLY+XBI+IEF+TLT+GLD&singleAbsoluteMomentum=false&volatilityTarget=9.0&downsideVolatility=false&outOfMarketStartMonth=5&outOfMarketEndMonth=10&outOfMarketAssetType=1&movingAverageSignal=1&movingAverageType=1&multipleTimingPeriods=false&periodWeighting=2&windowSize=1&windowSizeInDays=105&movingAverageType2=1&windowSize2=10&windowSizeInDays2=105&excludePreviousMonth=false&normalizeReturns=false&volatilityWindowSize=-1&volatilityWindowSizeInDays=21&assetsToHold=4&allocationWeights=4&riskControlType=0&riskWindowSize=10&riskWindowSizeInDays=0&rebalancePeriod=1&separateSignalAsset=false&tradeExecution=0&comparedAllocation=0&benchmark=-1&benchmarkSymbol=SPY&timingPeriods%5B0%5D=5&timingUnits%5B0%5D=2&timingWeights%5B0%5D=100&timingUnits%5B1%5D=2&timingWeights%5B1%5D=0&timingUnits%5B2%5D=2&timingWeights%5B2%5D=0&timingUnits%5B3%5D=2&timingWeights%5B3%5D=0&timingUnits%5B4%5D=2&timingWeights%5B4%5D=0&volatilityPeriodUnit=1&volatilityPeriodWeight=0'
  BALANCED: ['QQQ', 'QCLN', 'FDN', 'XLY', 'TLT'] # RS-1m, VOl-21d, 3/5 to hold
# 'https://www.portfoliovisualizer.com/test-market-timing-model?s=y&coreSatellite=false&timingModel=9&timePeriod=2&startYear=2007&firstMonth=1&endYear=2020&lastMonth=12&calendarAligned=true&includeYTD=false&initialAmount=10000&periodicAdjustment=0&adjustmentAmount=0&inflationAdjusted=true&adjustmentPercentage=0.0&adjustmentFrequency=4&symbols=QQQ+QCLN+FDN+XLY+TLT&singleAbsoluteMomentum=false&volatilityTarget=25.0&downsideVolatility=false&outOfMarketStartMonth=5&outOfMarketEndMonth=10&outOfMarketAssetType=2&outOfMarketAsset=TLT&movingAverageSignal=1&movingAverageType=1&multipleTimingPeriods=false&periodWeighting=2&windowSize=1&windowSizeInDays=105&movingAverageType2=1&windowSize2=10&windowSizeInDays2=105&excludePreviousMonth=false&normalizeReturns=false&volatilityWindowSize=-1&volatilityWindowSizeInDays=21&assetsToHold=3&allocationWeights=4&riskControlType=0&riskWindowSize=10&riskWindowSizeInDays=0&rebalancePeriod=1&separateSignalAsset=false&tradeExecution=0&comparedAllocation=0&benchmark=-1&benchmarkSymbol=QQQ&timingPeriods%5B0%5D=5&timingUnits%5B0%5D=2&timingWeights%5B0%5D=100&timingUnits%5B1%5D=2&timingWeights%5B1%5D=0&timingUnits%5B2%5D=2&timingWeights%5B2%5D=0&timingUnits%5B3%5D=2&timingWeights%5B3%5D=0&timingUnits%5B4%5D=2&timingWeights%5B4%5D=0&volatilityPeriodUnit=2&volatilityPeriodWeight=0&symbol1=QQQ&allocation1_1=25&symbol2=QCLN&allocation2_1=25&symbol3=FDN&allocation3_1=25&symbol4=FPX&allocation4_1=25'
#  AGGRESSIVE: ['ARKW', 'QQQ', 'QCLN', 'XBI', 'FDN', 'TLT'] # RS-1m, VOl-21d, 3/6 to hold
  AGGRESSIVE: ['QLD', 'QQQ', 'QCLN', 'XBI', 'FDN', 'TLT'] # RS-1m, VOl-21d, 3/6 to hold HISTORY!!!!!!!
# 'https://www.portfoliovisualizer.com/test-market-timing-model?s=y&coreSatellite=false&timingModel=9&timePeriod=2&startYear=2007&firstMonth=1&endYear=2020&lastMonth=12&calendarAligned=true&includeYTD=false&initialAmount=10000&periodicAdjustment=0&adjustmentAmount=0&inflationAdjusted=true&adjustmentPercentage=0.0&adjustmentFrequency=4&symbols=ARKW+QQQ+QCLN+XBI+FDN+TLT&singleAbsoluteMomentum=false&volatilityTarget=9.0&downsideVolatility=false&outOfMarketStartMonth=5&outOfMarketEndMonth=10&outOfMarketAssetType=1&movingAverageSignal=1&movingAverageType=1&multipleTimingPeriods=false&periodWeighting=1&windowSize=1&windowSizeInDays=105&movingAverageType2=1&windowSize2=10&windowSizeInDays2=105&excludePreviousMonth=false&normalizeReturns=false&volatilityWindowSize=-1&volatilityWindowSizeInDays=21&assetsToHold=3&allocationWeights=4&riskControlType=0&riskWindowSize=10&riskWindowSizeInDays=0&rebalancePeriod=1&separateSignalAsset=false&tradeExecution=0&comparedAllocation=0&benchmark=-1&benchmarkSymbol=QQQ&timingPeriods%5B0%5D=3&timingUnits%5B0%5D=2&timingWeights%5B0%5D=50&timingPeriods%5B1%5D=21&timingUnits%5B1%5D=1&timingWeights%5B1%5D=50&timingUnits%5B2%5D=2&timingWeights%5B2%5D=0&timingUnits%5B3%5D=2&timingWeights%5B3%5D=0&timingUnits%5B4%5D=2&timingWeights%5B4%5D=0&volatilityPeriodUnit=1&volatilityPeriodWeight=0'
# 'https://www.portfoliovisualizer.com/test-market-timing-model?s=y&coreSatellite=false&timingModel=9&timePeriod=2&startYear=2007&firstMonth=1&endYear=2020&lastMonth=12&calendarAligned=true&includeYTD=false&initialAmount=10000&periodicAdjustment=0&adjustmentAmount=0&inflationAdjusted=true&adjustmentPercentage=0.0&adjustmentFrequency=4&symbols=QLD+QQQ+QCLN+XBI+FDN+TLT&singleAbsoluteMomentum=false&volatilityTarget=9.0&downsideVolatility=false&outOfMarketStartMonth=5&outOfMarketEndMonth=10&outOfMarketAssetType=1&movingAverageSignal=1&movingAverageType=1&multipleTimingPeriods=false&periodWeighting=1&windowSize=1&windowSizeInDays=105&movingAverageType2=1&windowSize2=10&windowSizeInDays2=105&excludePreviousMonth=false&normalizeReturns=false&volatilityWindowSize=-1&volatilityWindowSizeInDays=21&assetsToHold=3&allocationWeights=4&riskControlType=0&riskWindowSize=10&riskWindowSizeInDays=0&rebalancePeriod=1&separateSignalAsset=false&tradeExecution=0&comparedAllocation=0&benchmark=-1&benchmarkSymbol=QQQ&timingPeriods%5B0%5D=3&timingUnits%5B0%5D=2&timingWeights%5B0%5D=50&timingPeriods%5B1%5D=21&timingUnits%5B1%5D=1&timingWeights%5B1%5D=50&timingUnits%5B2%5D=2&timingWeights%5B2%5D=0&timingUnits%5B3%5D=2&timingWeights%5B3%5D=0&timingUnits%5B4%5D=2&timingWeights%5B4%5D=0&volatilityPeriodUnit=1&volatilityPeriodWeight=0'
#  LEVERAGED: ['ARKW', 'FDN', 'QCLN', 'TMF'] # RS-1m, VOl-21d, 3/4 to hold
  LEVERAGED: [ 'QLD', 'FDN', 'QCLN', 'TMF' ] # RS-1m, VOl-21d, 3/4 to hold HISTORY!!!!!!!


  TEST_ADM: ['QLD', 'QQQ', 'XBI', 'XLY', 'FDN', 'QCLN', 'TLT']

# 'https://www.portfoliovisualizer.com/test-market-timing-model?s=y&coreSatellite=false&timingModel=9&timePeriod=2&startYear=2010&firstMonth=1&endYear=2020&lastMonth=12&calendarAligned=true&includeYTD=false&initialAmount=10000&periodicAdjustment=0&adjustmentAmount=0&inflationAdjusted=true&adjustmentPercentage=0.0&adjustmentFrequency=4&symbols=ARKW+SSO+QQQ+TMF&singleAbsoluteMomentum=false&volatilityTarget=20.0&downsideVolatility=false&outOfMarketStartMonth=5&outOfMarketEndMonth=10&outOfMarketAssetType=2&outOfMarketAsset=TLT&movingAverageSignal=1&movingAverageType=1&multipleTimingPeriods=false&periodWeighting=2&windowSize=1&windowSizeInDays=105&movingAverageType2=1&windowSize2=10&windowSizeInDays2=105&excludePreviousMonth=false&normalizeReturns=false&volatilityWindowSize=-1&volatilityWindowSizeInDays=21&assetsToHold=3&allocationWeights=4&riskControlType=0&riskWindowSize=10&riskWindowSizeInDays=0&rebalancePeriod=1&separateSignalAsset=false&tradeExecution=0&comparedAllocation=0&benchmark=-1&benchmarkSymbol=QQQ&timingPeriods%5B0%5D=5&timingUnits%5B0%5D=2&timingWeights%5B0%5D=100&timingUnits%5B1%5D=2&timingWeights%5B1%5D=0&timingUnits%5B2%5D=2&timingWeights%5B2%5D=0&timingUnits%5B3%5D=2&timingWeights%5B3%5D=0&timingUnits%5B4%5D=2&timingWeights%5B4%5D=0&volatilityPeriodUnit=2&volatilityPeriodWeight=0&symbol1=QLD&allocation1_1=35&symbol2=SSO&allocation2_1=15&symbol3=TMF&symbol4=TLT&allocation4_1=50'
# 'https://www.portfoliovisualizer.com/test-market-timing-model?s=y&coreSatellite=false&timingModel=9&timePeriod=2&startYear=2010&firstMonth=1&endYear=2020&lastMonth=12&calendarAligned=true&includeYTD=false&initialAmount=10000&periodicAdjustment=0&adjustmentAmount=0&inflationAdjusted=true&adjustmentPercentage=0.0&adjustmentFrequency=4&symbols=QLD+SSO+QQQ+TMF&singleAbsoluteMomentum=false&volatilityTarget=20.0&downsideVolatility=false&outOfMarketStartMonth=5&outOfMarketEndMonth=10&outOfMarketAssetType=2&outOfMarketAsset=TLT&movingAverageSignal=1&movingAverageType=1&multipleTimingPeriods=false&periodWeighting=2&windowSize=1&windowSizeInDays=105&movingAverageType2=1&windowSize2=10&windowSizeInDays2=105&excludePreviousMonth=false&normalizeReturns=false&volatilityWindowSize=-1&volatilityWindowSizeInDays=21&assetsToHold=3&allocationWeights=4&riskControlType=0&riskWindowSize=10&riskWindowSizeInDays=0&rebalancePeriod=1&separateSignalAsset=false&tradeExecution=0&comparedAllocation=0&benchmark=-1&benchmarkSymbol=QQQ&timingPeriods%5B0%5D=5&timingUnits%5B0%5D=2&timingWeights%5B0%5D=100&timingUnits%5B1%5D=2&timingWeights%5B1%5D=0&timingUnits%5B2%5D=2&timingWeights%5B2%5D=0&timingUnits%5B3%5D=2&timingWeights%5B3%5D=0&timingUnits%5B4%5D=2&timingWeights%5B4%5D=0&volatilityPeriodUnit=2&volatilityPeriodWeight=0&symbol1=QLD&allocation1_1=35&symbol2=SSO&allocation2_1=15&symbol3=TMF&symbol4=TLT&allocation4_1=50'
